### ISSUE TITLE
Enrich organizations with geo data

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#141]
Organizations have an "HQ Location" field with no consistent formatting or specificity. We should use a 3rd party service to take these strings and convert them into consistently formatted location data. 

One primary concern here is that we're using a service with liberal licensing, such as [GeoNames](http://www.geonames.org/) or [OpenStreetMap](https://www.openstreetmap.org/).

The Organizations table should end up with three new columns:

* Country
* State (there may be a more international-friendly name for this)
* City

**Comment by bloudermilk** [comment]
Related to #92

**Comment by loiclefloch** [comment]
This is something I can work on.

Before I begin, since I am not familiar with the backend codebase yet, I will have some questions.

First, is this feature considered as an "airtable enrichment" like the `rank.js` code? In this case I would add the data in prepareEnrichmentFields like the `Rank` data?
