### ISSUE TITLE
Conflicting organization slugs

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#272]
Planet and Planet+ have conflicting slugs

**Comment by loiclefloch** [comment]
I am working on it. The problem comes from the way we generate our slug. When there is a non-alphanumeric character, we delete the char (here the `+`).
The question is how we should better handle the slug generation to handle the `+` and maybe other characters. I could just handle the `+` but we could have the same problem with organization's names using non-alphanumeric chars.
Event if the chances are low, I think we should handle it properly.

(in the following, `+` can be replaced by any non-alphanumeric char if we decide to handle them)

- Should we keep the `+`?
- Should we replace `+` by something like `-`?

**Comment by bloudermilk** [comment]
@loiclefloch I address your questions above in #275.
