### ISSUE TITLE
Implement server to support dynamic user features

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#278]
The upcoming Lists feature requires a dynamic backend to auth users and persist data.

We should take the following goals into consideration:

* Optimize for developer productivity
* Keep parity with current stack (i.e. use GraphQL)
* Should be reliable & low-maintenance
* Avoid vendor lock-in

After researching various options over the past couple of weeks, I'm favoring [Hasura](https://hasura.io/) as the candidate that meets all of the above goals. Hosting it on Heroku is incredibly easy and reliable.

**Comment by bloudermilk** [comment]
@jasonLaster @miriambudayr @loiclefloch your opinions wanted!

**Comment by loiclefloch** [comment]
## General concerns about GraphQL vs REST:

While GraphQL is really usefull for Gatsby and static website, I have some concern with a dynamic app. If we have to use Postgres I feel like using a REST API is better suited, using directly the Postgres database and avoiding to have another layer with GraphQL.

Note that I never used GraphQL for anything else that Gatsby projects. So the following is really personal.

REST:
- + lot of libraries
- + lot of documentation
- + generally known by any folks who made an API before
- - maybe too "old school" and would not make contributors feel like they are working on something cool

GraphQL:
- + keep consistency with Gatsby BUT this is a totally different project
- + looks "sexy"
- - force to use another project / library so it make things complicated
- - is still pretty new
- - could be difficult to handle for beginners
- ? I lack experience on it so I cannot say if it is really cool to have / easy to use instead of REST. But I feel like it would add some difficulty for contributors / maintaining the project with too many layers.

The big question to resume: do we want to use new tech that looks cool/trending and accept that it could possibly reduce contributions / make maintenance harder or keep with old tech that is easier for anyone to contribute on but could be seen as not really fun?

My experience is that we tend to use new technologies because they seem fun but it makes harder to maintain/code the project and it takes much time to develop. And because the contributors come and go on technologies that they do not know/master, the code is not really good and really hard to maintain. Most of the time its ends on a total refactor before being able to move forward with new features or improve existent features.

While it can be okay for a personal project I think it is not a good idea for a project where we want a community to work on it. We should make development the easier and fastest possible.

I tried to make this as easy to understand and and concise. But it raise some big questions for me on which tek to use, before thinking on what technology/libraries we should use.
Maybe some of those points have already been discussed, in that case can you point us on where we can see those discussions?


## Specific questions on Hasura:

- Needs a postres database. On Heroku? For which pricing?
- The tech seems pretty new, so it could be difficult for beginners to start with: not enough resources / tutorials / stackoverflow

**Comment by bloudermilk** [comment]
@loiclefloch thanks for bringing this up, I think it's important to discuss. I've worked with REST (implementing and consuming) for about a decade and agree with all the points you mentioned about it. It's tried and true, simple to understand, and generally has good support in all ecosystems.

I first tried GraphQL a couple of years ago and have since implemented several backends and consumed it across a few different projects, Climatescape being the most recent. I have to say, there aren't many scenarios where I would want to use REST over GraphQL. Here are the primary decision factors for me:

* Automatic fetching of relationships
* Less time spent debating "API styleguides"
* Clients can fetch as much/little as they want to
* Enforced type system/schema
* Great tooling that takes advantage of all the above "for free"

One thing I'll say is that of all the times I've used GraphQL, Gatsby has offered the worst implementation. It's generally very limited and the schema is not simple or easy to understand.

As far as Hasura goes, the premise of it is that it's the easiest way to implement a GraphQL backend. It's a "low-code" solution that should allow any developer to make changes to our DB schema without needing to know much about Postgres, GraphQL, or even how Hasura works. It's been on my radar for a while but [this thread](https://news.ycombinator.com/item?id=22787313) finally convinced me to give it a shot.

> Needs a postres database. On Heroku? For which pricing?

With this dynamic backend I don't think we'll be able to avoid incurring operational costs much longer. I'm in the process of applying for an [Open Collective](https://opencollective.com/) account for us to accept donations and track billing.

**Comment by bloudermilk** [comment]
@loiclefloch FYI I'm spending some time digging deeper into Hasura to assess the maturity of it. I think you make a really strong point here:

> The tech seems pretty new, so it could be difficult for beginners to start with: not enough resources / tutorials / stackoverflow

I'm trying to think through what features we'd need in the short/medium term and evaluate the support within Hasura.

I'm curious, what does your REST stack look like on NodeJS? I'm a big fan of Postgres as a database which is what led me to Hasura in the first place. But if we were going to develop our own API from scratch, what libraries would you use?

**Comment by bloudermilk** [comment]
For reference, the stack I've used to implement GraphQL before has been:

* [Apollo](https://www.apollographql.com/) for server/client
* Postgres
* [Sequelize](https://sequelize.org/)
* [Mocha](https://mochajs.org/) + [Chai](https://www.chaijs.com/) for testing
