### ISSUE TITLE
We should add better HQ Location fields

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#92]
We currently have HQ_Location, but the data is vague. It'd be nice to have HQ_Location_Country, HQ_Location_State, HQ_Location_City.

Similarly, HQ_Address might be nice because we could scrape that and then populate the other three.

**Comment by bloudermilk** [comment]
@jasonLaster we ended up with the concatenated "HQ Location" field because we couldn't reliably get it in the separated format. The plan is to use the backend @leventov is building to send these concatenated locations to a geocoding service (e.g. Google Places) for reliable component extraction. I imagine this is relevant to your work on the filter UI–we should hold off on the location component of that for now.

**Comment by bloudermilk** [comment]
This is done thanks to @loiclefloch
